"""Added column time_for_ai_answer

Revision ID: 2b22014a99a8
Revises: af33122354e2
Create Date: 2024-07-01 15:36:12.973758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b22014a99a8'
down_revision: Union[str, None] = 'af33122354e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('time_for_ai_answer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'time_for_ai_answer')
    # ### end Alembic commands ###
